### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by defineconst** [marsgis/mars3d-vue-project#1]
node -v
v14.19.0
npm -v
6.14.16
vue -Version
@vue/cli 5.0.1

PS npm run build

mars3d-vue-project@3.3.0 build mars3d-vue3-project
npm run lint && vite build

mars3d-vue-project@3.3.0 lint mars3d-vue3-project
eslint ./src/**/*.{js,jsx,vue,ts,tsx} --fix && vue-tsc --noEmit

mars3d-vue3-project\src\pages\demo\views\home.vue
1:1 error Component name "home" should always be multi-word vue/multi-word-component-names

mars3d-vue3-project\src\pages\demo\views\map.vue
1:1 error Component name "map" should always be multi-word vue/multi-word-component-names

mars3d-vue3-project\src\pages\demo\views\widget.vue
1:1 error Component name "widget" should always be multi-word vue/multi-word-component-names

mars3d-vue3-project\src\widgets\demo\menu\button.ce.vue
1:1 error Component name "button.ce" should always be multi-word vue/multi-word-component-names

✖ 4 problems (4 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mars3d-vue-project@3.3.0 lint: eslint ./src/**/*.{js,jsx,vue,ts,tsx} --fix && vue-tsc --noEmit
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mars3d-vue-project@3.3.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2022-05-03T22_06_37_784Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mars3d-vue-project@3.3.0 build: npm run lint && vite build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mars3d-vue-project@3.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2022-05-03T22_06_37_818Z-debug.log
10 silly lifecycle mars3d-vue-project@3.3.0build: Args: [ '/d /s /c', 'npm run lint && vite build' ]
11 silly lifecycle mars3d-vue-project@3.3.0build: Returned: code: 1 signal: null
12 info lifecycle mars3d-vue-project@3.3.0~build: Failed to exec build script
13 verbose stack Error: mars3d-vue-project@3.3.0 build: npm run lint && vite build
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (D:\nvm\v14.19.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:400:28)
13 verbose stack at ChildProcess. (D:\nvm\v14.19.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:400:28)
13 verbose stack at maybeClose (internal/child_process.js:1058:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid mars3d-vue-project@3.3.0
15 verbose cwd mars3d-vue3-project
16 verbose Windows_NT 10.0.17763
17 verbose argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
18 verbose node v14.19.0
19 verbose npm v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error mars3d-vue-project@3.3.0 build: npm run lint && vite build
22 error Exit status 1
23 error Failed at the mars3d-vue-project@3.3.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

src/widgets/basic/query-poi/map.ts:137:11 - error TS2322: Type '{ text: any; font_size: number; color: string; outline: true; outlineWidth: number; outlineColor: mars3d.Cesium.Color; horizontalOrigin: mars3d.Cesium.HorizontalOrigin.CENTER; ... 4 more ...; visibl
eDepth: false; }' is not assignable to type 'StyleOptions'.
Object literal may only specify known properties, and 'outline' does not exist in type 'StyleOptions'.

137 outline: true,
~~~~~~~~~~~~~

node_modules/mars3d/dist/mars3d.d.ts:9031:9
9031 label?: LabelEntity.StyleOptions;
~~~~~
The expected type comes from property 'label' which is declared here on type 'StyleOptions'

**Comment by muyao1987** [comment]
ts错误，已经解决，更新最新代码即可。
