### ISSUE TITLE
使用widget报错

### ISSUE THREAD

**Issue by Eva-Skye** [marsgis/mars3d-vue-project#3]
![image](https://user-images.githubusercontent.com/45868259/185337330-05a145c6-92ac-459b-8823-117250b881fd.png)

**Comment by Eva-Skye** [comment]
有没有开发人员可以回复一下...

**Comment by Eva-Skye** [comment]
![de9b861129b76baf7e4d5c2b14519e5](https://user-images.githubusercontent.com/45868259/185580625-4079dd95-bd38-466f-8824-2d711e4a4c93.jpg)
有人嘛

**Comment by niujunjier** [comment]
需要再vite.config.js中添加如下配置
`optimizeDeps: {
      include: ["widget.js 的路径"]
    },`

**Comment by Eva-Skye** [comment]
好的感谢
