### ISSUE TITLE
使用原生cesium开发的问题

### ISSUE THREAD

**Issue by Eva-Skye** [marsgis/mars3d-vue-project#4]
我看到示例中提供了原生cesium的开发方式，如图
![image](https://user-images.githubusercontent.com/45868259/187814811-7a5b3505-0a7e-427f-b4a1-3edc60ac51ff.png)
请问这个工程是否可以实现使用原生cesium创建地球呢，我尝试了一下，发现使用cesium的viewer后，widget全出错了

**Comment by Eva-Skye** [comment]
原本
![image](https://user-images.githubusercontent.com/45868259/187816168-c4e372ef-41f1-4d38-830d-6a7a4cece7d3.png)
换成cesium的viewer
![image](https://user-images.githubusercontent.com/45868259/187816077-4b047104-1768-4755-829c-f3d93749f555.png)

**Comment by Eva-Skye** [comment]
哥哥们，救命，数据配置json没有改，我看拿到的basemap是空的，有的救吗

**Comment by Eva-Skye** [comment]
解决了 它和cesium的地图配置冲突了，得去除掉cesium的baseLayerPicker

**Comment by muyao1987** [comment]
是的，是baseLayerPicker打开后走了原生Cesium那套逻辑。

**Comment by Eva-Skye** [comment]
@muyao1987 不好意思再打扰一下，这里的cesium必须是mars提供的cesium么，我使用原生1.97的cesium，在模板工程中，模板中做好的widget会失效，不知是不是有什么限制？

**Comment by muyao1987** [comment]
不需要的，widget这块逻辑与cesium无关的。并且超图示例中也是用超图版cesium的。https://github.com/marsgis/mars3d-link-supermap/tree/master/mars3d-vue-project

**Comment by Eva-Skye** [comment]
@muyao1987 
这是我刚从[https://github.com/marsgis/mars3d-vue-project](url)拉下来的代码
只引入了1.98的ceisum，在mars-map中这么来加载，但是有报错，我就以为不能用原生ceisum了
![image](https://user-images.githubusercontent.com/45868259/194733250-98ba6091-45b2-4a3e-8cc7-4c241963257b.png)
![image](https://user-images.githubusercontent.com/45868259/194733266-47bf1154-4b48-4dbb-b7dc-e14429c2953d.png)

**Comment by muyao1987** [comment]
因为cesium的1.97将3dtiles全改了，目前还没用，你切换ceisum到1.96看看

**Comment by Eva-Skye** [comment]
@muyao1987 我之前看到官网示例用1.96的时候就有换过版本进行测试噢，
![image](https://user-images.githubusercontent.com/45868259/194742571-c25aca11-2652-4df2-b2fb-ef2776da06d7.png)
还是一样的报错，不过现在在npm上的mars3d版本和官网示例不一样
